### PR TITLE
SPIKE: Rename store to emstore and data-adapter to em-data-adapter

### PR DESCRIPTION
**Pull request by nolaneo**

### CODE REVIEW

**Comment by GavinJoyce** [comment]
@nolaneo we're currently pinned to this version which means that we wont benefit from upstream changes. Perhaps we could come up with a plan to contribute this to ember-model?

**Comment by GavinJoyce** [comment]
@paddyobrien should [your changes](https://github.com/intercom/ember-model/pull/3/commits/fba009b03995a74d72c223d162a8a26959358b47) be submitted to upstream too? It would be nice for us to get back on master

**Comment by paddyobrien** [comment]
My changes are already upstream (they're just a result of me building the lib)

**Comment by GavinJoyce** [comment]
As we're likely to use ember-model for the foreseeable future, we should plan to push these changes upstream and get back on master.

I chatted with @nolaneo about this and he'd like to wait until the Beckett editor has shipped as it will remove an area where we have significant ember model dirty tracking hacks. In the mean time, I'll push some small changes to the branch to fix deprecation warnings.

@nolaneo is this something that you can put on the roadmap once Beckett has shipped?

**Pull request closed without merging**
