### PR TITLE
Rename store and adapter

### PR DESCRIPTION
**Pull request by kmiyashiro**
@nolaneo I had to re-create this commit to fix deploys because your original one was no longer reachable from the tree. Should this be merged into master? Seems reasonable since we are using in production.

### CODE REVIEW

**Comment by nolaneo** [comment]
Thanks @kmiyashiro. I don't have strong options about merging it to master or not; it might be better to leave as a separate branch so we can pull in upstream changes more easily? (opinions @GavinJoyce?)

We're trying to get it merged upstream here: https://github.com/ebryn/ember-model/pull/454

**Comment by GavinJoyce** [comment]
Perhaps let's leave it in a branch in `intercom/ember-model` and reference that in bower instead of a SHA?. That will allow us to pull in upstream changes to `intercom/ember-model` as needed and rebase this PR when we want to update

**Comment by GavinJoyce** [comment]
I'm going to clean up our `intercom/ember-model` fork as it has diverged from origin. Once I've done that, we can point to a named branch which we can rebase against new origin changes as required.

First step: https://github.com/intercom/embercom/pull/17620

**Comment by GavinJoyce** [comment]
We're no longer pointing at this sha

**Pull request closed without merging**
